import { useEffect, useMemo, useState } from "react";
import { Box, Button, Code, Heading, HStack, Text, VStack } from "@chakra-ui/react";
import { getClient } from "../amplifyClient";
import { getCurrentUser } from "aws-amplify/auth";
import { TaskStatus, TaskPriority } from "../API";

// These are generated by `amplify codegen`
import {
  createTaskListMinimal,
  createTaskMinimal,
  listTaskListsMinimal,
  tasksByListMinimal,
} from "../graphql/operations";

import { fetchAuthSession } from "aws-amplify/auth";


type LogLine = { at: string; msg: string; data?: unknown };
type GenOp = string & {
  __generatedQueryOutput?: unknown;
  __generatedMutationOutput?: unknown;
};


type OpOut<T extends GenOp> =
  T extends { __generatedMutationOutput: infer O } ? O :
  T extends { __generatedQueryOutput: infer O } ? O :
  never
;

type AmplifyGraphQLClient = ReturnType<typeof getClient>;

async function runOp<T extends GenOp>(
  client: AmplifyGraphQLClient,
  query: T,
  /* eslint-disable @typescript-eslint/no-explicit-any */
  variables?: any
) {
  const res = (await client.graphql({ query, variables })) as { data?: OpOut<T> };
  return res.data;
}

export function GraphQLSmokeTest() {
  const client = useMemo(() => getClient(), []);
  const [log, setLog] = useState<LogLine[]>([]);
  const [lastListId, setLastListId] = useState<string | null>(null);

  const pushLog = (msg: string, data?: unknown) =>
    setLog((prev) => [{ at: new Date().toLocaleTimeString(), msg, data }, ...prev]);

  useEffect(() => {
    (async () => {
      try {
        const user = await getCurrentUser();
        pushLog("Signed in user detected ✅", user);
      } catch (e) {
        pushLog("No signed in user ❌ (sign in first)", e);
      }
    })();
  }, []);

  async function runCreateListAndTask() {
    try {
      /* eslint-disable @typescript-eslint/no-explicit-any */
      const listData =
        await runOp(client, createTaskListMinimal as any, {
          input: {
            name: `Inbox (${new Date().toLocaleTimeString()})`,
            isFavorite: false,
            sortOrder: 1,
          },
        });

      /* eslint-disable @typescript-eslint/no-explicit-any */
      const createdList = (listData as any)?.createTaskList;
      if (!createdList?.id) throw new Error("createTaskList did not return an id");

      pushLog("Created TaskList ✅", createdList);
      setLastListId(createdList.id);

      /* eslint-disable @typescript-eslint/no-explicit-any */
      const taskData = await runOp(client, createTaskMinimal as any, {
        input: {
          listId: createdList.id,
          sortOrder: 1,
          title: "Hello GraphQL",
          description: "Smoke test task",
          status: TaskStatus.Open,
          priority: TaskPriority.Medium,
          tagIds: [],
        },
      });

      pushLog("Created Task ✅", (taskData as any)?.createTask);
    } catch (e) {
      pushLog("Create list/task failed ❌", e);
    }
  }

  async function runListLists() {
    try {
      const data = await runOp(client, listTaskListsMinimal, { limit: 20 });
      const items = data?.listTaskLists?.items ?? [];
      pushLog(`Fetched TaskLists ✅ (count=${items.length})`, items);
    } catch (e) {
      pushLog("List TaskLists failed ❌", e);
    }
  }

  async function runTasksByList() {
    if (!lastListId) {
      pushLog("No lastListId yet — create a list first.");
      return;
    }

    try {
      const data = await runOp(client, tasksByListMinimal, {
        listId: lastListId,
        sortOrder: { ge: 0 },
        limit: 50,
      });

    const items = data?.tasksByList?.items ?? [];
      pushLog(`Fetched tasksByList ✅ (count=${items.length})`, items);
    } catch (e) {
      pushLog("tasksByList failed ❌", e);
    }
  }

  async function fetchAndLogAuthSession() {
    const s = await fetchAuthSession({ forceRefresh: true });
    console.log(s.tokens?.idToken?.payload);
  }

  return (
    <VStack align="start" gap={4} p={4} bg="white" rounded="md" boxShadow="sm">
      <Heading size="md">GraphQL Smoke Test</Heading>
      <Button
        variant={"outline"}
        onClick={fetchAndLogAuthSession}
      >Check status</Button>
      <Text color="gray.600">
        Quick end-to-end checks for Cognito + AppSync + @model/@auth(owner).
      </Text>

      <HStack>
        <Button onClick={runCreateListAndTask}>1) Create List + Task</Button>
        <Button variant="outline" onClick={runListLists}>
          2) List TaskLists
        </Button>
        <Button variant="outline" onClick={runTasksByList} disabled={!lastListId}>
          3) tasksByList (last created list)
        </Button>
      </HStack>

      {lastListId ? (
        <Text fontSize="sm" color="gray.600">
          lastListId: <Code>{lastListId}</Code>
        </Text>
      ) : null}

      <Box w="100%">
        <Heading size="sm" mb={2}>
          Log
        </Heading>
        <VStack align="stretch" gap={2}>
          {log.map((l, idx) => (
            <Box key={idx} borderWidth="1px" rounded="md" p={2}>
              <Text fontSize="sm" color="gray.500">
                {l.at}
              </Text>
              <Text fontWeight="600">{l.msg}</Text>
              {l.data !== undefined ? (
                <Box mt={2} maxH="220px" overflow="auto" bg="gray.50" p={2} rounded="md">
                  <pre style={{ fontSize: 12, margin: 0 }}>{JSON.stringify(l.data, null, 2)}</pre>
                </Box>
              ) : null}
            </Box>
          ))}
        </VStack>
      </Box>
    </VStack>
  );
}